# Generated by Django 3.1.4 on 2021-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_blog_rating_userredirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('post_code', models.IntegerField()),
                ('door_number', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
