# Generated by Django 3.1.4 on 2021-02-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210213_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
