# Generated by Django 3.1.4 on 2021-02-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210215_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
