# Generated by Django 3.1.4 on 2021-02-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metainfo',
            old_name='appliance_description',
            new_name='broadband_description',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='appliance_name',
            new_name='broadband_name',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='appliance_title',
            new_name='broadband_title',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='design_description',
            new_name='dual_sim_description',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='design_name',
            new_name='dual_sim_name',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='design_title',
            new_name='dual_sim_title',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='install_description',
            new_name='monthly_deals_description',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='install_name',
            new_name='monthly_deals_name',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='install_title',
            new_name='monthly_deals_title',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='kitchen_description',
            new_name='online_shop_description',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='kitchen_name',
            new_name='online_shop_name',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='kitchen_title',
            new_name='online_shop_title',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='worktop_description',
            new_name='wifi_description',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='worktop_title',
            new_name='wifi_name',
        ),
        migrations.RenameField(
            model_name='metainfo',
            old_name='worktop_name',
            new_name='wifi_title',
        ),
    ]
