# Generated by Django 3.1.4 on 2021-04-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_cart_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(default='decxription'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='blog_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='blog_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='blogs_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='login_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='login_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='login_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='signup_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='signup_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='signup_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='wishlist_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='wishlist_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='wishlist_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
