# Generated by Django 3.1.4 on 2021-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20210407_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='metainfo',
            name='mission_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='mission_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='mission_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='privacy_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='privacy_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='privacy_title',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='terms_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='terms_name',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='metainfo',
            name='terms_title',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
