# Generated by Django 3.1.4 on 2021-07-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20210717_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='averageRating',
        ),
    ]
