# Generated by Django 3.1.4 on 2021-07-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20210717_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='learn_more',
            field=models.TextField(blank=True, null=True),
        ),
    ]
