# Generated by Django 3.1.4 on 2021-07-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210719_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='learn_more',
        ),
    ]
